### ISSUE TITLE
externals\modified_e2e_coref\coref_kernels.so not found

### ISSUE THREAD

**Issue by TianxingWang0** [sattree/gap#2]
Hello, I cloned your repo and installed all python packages, when I enter the preprocess command it has this error. I am using Windows.

**Comment by sattree** [comment]
Hi, please refer to the instructions on https://github.com/kentonl/e2e-coref to generate coref_kernels.so. The file is generated by running 'setup_all.sh' available in the project root.

This is a binary file that's compiled for a particular platform and even if I checked in a version, it may not be of much help.

Alternatively, you could switch the flag to --model=probert in preprocess command if you are not specifically looking to use the grep model architecture.

**Comment by TianxingWang0** [comment]
What a quick response! I am intended to use your fascinating GREP model, so I will try to figure it out.

**Comment by sattree** [comment]
Sure, happened to see the notification.

There are some moving parts in the preprocess command but once you figure them out then everything else is smooth there on. Allennlp models are straightforward to run. You just have to make sure you can get e2e-coref and stanford models up and running.

Let me know how it goes. I'm happy to help!

**Comment by TianxingWang0** [comment]
Thanks a lot!
